### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by yairEO** [yishayhaz/adva-effect#1]
Hi, I've made improvements to your code:

https://codepen.io/vsync/pen/bGvEeQb

## JS:

1. First and most importantly, wrap the code with a self-invoking function to encapsulate the content
2. Second and also highly important - do not bind events directly on elements, but use event-delegation, which is more efficient, and also supports dynamically-created elements.
3. Removed unneeded `if` statements for the `x` & `y` placements. 
4. You must name your CSS variables in a way which will have minimum chance for collusion with any possible variable that might already exist on the element, so it's a very good idea to *namespace* them: `--adva-x` & `--adva-y`. 
5. Moved animation duration to the CSS. Only the bare minimum should be controlled by javascript. You already have a CSS file so it makes sense for animation-related styles to all be defined there.

## CSS:
1. Removed unneeded `ratio` property
2. Added `filter: blur(20px);` & `mix-blend-mode: color-dodge;` for a much cooler effect. `blend-mode` is perfect for such things.
3. For keyframes, it's shorter to write `to` than `100%` ;)

**Comment by yishayhaz** [comment]
Hey @yairEO , thank you so much! i'll work on that:)

1. js[1 & 2] - Why are those so important? What conflicts they can create?
3. Why can I delete the "aspect-ratio" - it keeps the height=width, isn't it?
4. at css[2] - let me learn those css-rules, then i'll be comfortable adding them to my code 😅

**Comment by yairEO** [comment]
1. Defining things on the global context should be avoided unless it's intentional. [Read mode](https://stackoverflow.com/a/592414/104380)

2. You can see in my Codepen it's not needed. I don't understand why you thought it was ever needed, its extremely rare to need `aspect-ratio` and in your situation you don't even need to define `width` or `height` at all!, this is the beauty of the pseudo-element's `top` & `left` - because it's positioned absolutely, then think of it as a 1x1 pixel being placed **exactly** when the user clicked (each time) and since it has no `overflow` it will just grow and fade

3. These are old and known... basic CSS for years :)
